### PR TITLE
Updated Sample to include support for iOS4.3+

### PR DESCRIPTION
**Pull request by daveingle**
The iOS target was 6.0. I was wanting to test it out against an iOS target of 5.0.

Using CocoaPods:
[!] IODProfanityFilter (1.0.0) is not compatible with iOS 4.3.
[!] IODProfanityFilter (1.0.0) is not compatible with iOS 5.0.

I think the only post 4.3 version requirements were autolayout, storyboards and the weak outlets in the sample project.

### CODE REVIEW

**Comment by MigrantP** [comment]
Is this really necessary? It's just a very simple sample project to show you how the component works; it doesn't need to run on old SDK versions.

**Comment by daveingle** [comment]
You're right that it doesn't need to run on older SDK versions, but by including it in the pod means that you cant install the dependency in an app running 6.0-. The podspec target iOS version wont allow you.

There are two options in my opinion: 
1. Package the sample in the pod with the same SDK version as the rest of the source.
2. Don't package the sample in the pod.

I think option 2 is the way to go, there is less bloat inside the component. If I was to use it in my source, the sample  project being pulled every time I update my pods is not optimal. This pull request allows for option 1.

**Comment by MigrantP** [comment]
Option 2 is the way it already is. The sample is not included in the podspec.

The deployment target of the podspec could be changed, if it 100% works on older versions. I used iOS 6.0 because that's what I develop on and didn't care about testing it on old versions.

**Comment by daveingle** [comment]
I didn't get cocoapods to resolve the dependency for my target iOS version, so I forked the repo to lower the target. I incorrectly assumed that the sample was being packaged, from my investigation there was no iOS 6.0 requirements in the actual component. I'll close the pull request.

I think there would be value in giving it a round of testing on iOS 5, and lowering the deployment target.

**Pull request closed without merging**
